package com.newpipeweb.services

import com.newpipeweb.models.*
import org.schabi.newpipe.extractor.ServiceList.YouTube
import org.schabi.newpipe.extractor.comments.CommentsInfo
import org.schabi.newpipe.extractor.search.SearchInfo
import org.schabi.newpipe.extractor.stream.StreamInfo
import org.schabi.newpipe.extractor.stream.VideoStream
import org.schabi.newpipe.extractor.stream.AudioStream
import org.schabi.newpipe.extractor.channel.ChannelInfo
import org.schabi.newpipe.extractor.kiosk.KioskInfo

object YouTubeService {

    // ─────────────────────────────────────────
    // SEARCH
    // ─────────────────────────────────────────

    fun search(query: String): SearchModel {
        val searchInfo = SearchInfo.getInfo(
            YouTube,
            YouTube.searchQHFactory.fromQuery(query)
        )

        val items = searchInfo.relatedItems
            .filterNotNull()
            .mapNotNull { item ->
                try {
                    VideoModel(
                        id = extractVideoId(item.url),
                        title = item.name ?: "Unknown",
                        uploader = item.uploaderName ?: "Unknown",
                        uploaderUrl = item.uploaderUrl ?: "",
                        duration = item.duration,
                        viewCount = item.viewCount,
                        uploadDate = item.textualUploadDate ?: "",
                        thumbnailUrl = item.thumbnails.firstOrNull()?.url ?: "",
                        isLive = item.isLive,
                        url = item.url ?: ""
                    )
                } catch (e: Exception) {
                    null // skip malformed items
                }
            }

        return SearchModel(
            query = query,
            items = items,
            nextPage = searchInfo.nextPage?.url
        )
    }

    // ─────────────────────────────────────────
    // VIDEO INFO
    // ─────────────────────────────────────────

    fun getVideo(videoId: String): VideoModel {
        val url = "https://www.youtube.com/watch?v=$videoId"
        val streamInfo = StreamInfo.getInfo(YouTube, url)

        return VideoModel(
            id = videoId,
            title = streamInfo.name,
            uploader = streamInfo.uploaderName,
            uploaderUrl = streamInfo.uploaderUrl,
            duration = streamInfo.duration,
            viewCount = streamInfo.viewCount,
            uploadDate = streamInfo.textualUploadDate ?: "",
            thumbnailUrl = streamInfo.thumbnails.firstOrNull()?.url ?: "",
            description = streamInfo.description?.content ?: "",
            isLive = streamInfo.isLive,
            url = url
        )
    }

    // ─────────────────────────────────────────
    // STREAM URLs (actual playable links)
    // ─────────────────────────────────────────

    fun getStreams(videoId: String): StreamModel {
        val url = "https://www.youtube.com/watch?v=$videoId"
        val streamInfo = StreamInfo.getInfo(YouTube, url)

        val videoStreams = streamInfo.videoStreams.map { stream ->
            StreamUrl(
                url = stream.content,
                quality = stream.resolution,
                format = stream.format?.name ?: "UNKNOWN",
                isVideoOnly = false
            )
        } + streamInfo.videoOnlyStreams.map { stream ->
            StreamUrl(
                url = stream.content,
                quality = stream.resolution,
                format = stream.format?.name ?: "UNKNOWN",
                isVideoOnly = true
            )
        }

        val audioStreams = streamInfo.audioStreams.map { stream ->
            StreamUrl(
                url = stream.content,
                quality = "${stream.averageBitrate}kbps",
                format = stream.format?.name ?: "UNKNOWN",
                isVideoOnly = false
            )
        }

        val subtitles = streamInfo.subtitles.map { sub ->
            SubtitleTrack(
                url = sub.content,
                languageCode = sub.languageTag ?: "unknown",
                languageName = sub.displayLanguageName ?: sub.languageTag ?: "Unknown",
                isAutoGenerated = sub.isAutoGenerated
            )
        }

        val related = streamInfo.relatedItems
            .filterNotNull()
            .take(20)
            .mapNotNull { item ->
                try {
                    VideoModel(
                        id = extractVideoId(item.url),
                        title = item.name ?: "Unknown",
                        uploader = item.uploaderName ?: "Unknown",
                        uploaderUrl = item.uploaderUrl ?: "",
                        duration = item.duration,
                        viewCount = item.viewCount,
                        uploadDate = item.textualUploadDate ?: "",
                        thumbnailUrl = item.thumbnails.firstOrNull()?.url ?: "",
                        isLive = item.isLive,
                        url = item.url ?: ""
                    )
                } catch (e: Exception) {
                    null
                }
            }

        return StreamModel(
            id = videoId,
            title = streamInfo.name,
            uploader = streamInfo.uploaderName,
            duration = streamInfo.duration,
            videoStreams = videoStreams,
            audioStreams = audioStreams,
            hlsUrl = streamInfo.hlsUrl,
            subtitles = subtitles,
            relatedVideos = related
        )
    }

    // ─────────────────────────────────────────
    // CHANNEL
    // ─────────────────────────────────────────

    fun getChannel(channelId: String): ChannelModel {
        val url = "https://www.youtube.com/channel/$channelId"
        val channelInfo = ChannelInfo.getInfo(YouTube, url)

        val videos = channelInfo.relatedItems
            .filterNotNull()
            .take(30)
            .mapNotNull { item ->
                try {
                    VideoModel(
                        id = extractVideoId(item.url),
                        title = item.name ?: "Unknown",
                        uploader = channelInfo.name,
                        uploaderUrl = channelInfo.url,
                        duration = item.duration,
                        viewCount = item.viewCount,
                        uploadDate = item.textualUploadDate ?: "",
                        thumbnailUrl = item.thumbnails.firstOrNull()?.url ?: "",
                        isLive = item.isLive,
                        url = item.url ?: ""
                    )
                } catch (e: Exception) {
                    null
                }
            }

        return ChannelModel(
            id = channelId,
            name = channelInfo.name,
            url = channelInfo.url,
            description = channelInfo.description ?: "",
            subscriberCount = channelInfo.subscriberCount,
            avatarUrl = channelInfo.avatars.firstOrNull()?.url ?: "",
            bannerUrl = channelInfo.banners.firstOrNull()?.url ?: "",
            videos = videos
        )
    }

    // ─────────────────────────────────────────
    // TRENDING
    // ─────────────────────────────────────────

    fun getTrending(): List<VideoModel> {
        val kioskInfo = KioskInfo.getInfo(YouTube, "https://www.youtube.com/feed/trending")

        return kioskInfo.relatedItems
            .filterNotNull()
            .take(30)
            .mapNotNull { item ->
                try {
                    VideoModel(
                        id = extractVideoId(item.url),
                        title = item.name ?: "Unknown",
                        uploader = item.uploaderName ?: "Unknown",
                        uploaderUrl = item.uploaderUrl ?: "",
                        duration = item.duration,
                        viewCount = item.viewCount,
                        uploadDate = item.textualUploadDate ?: "",
                        thumbnailUrl = item.thumbnails.firstOrNull()?.url ?: "",
                        isLive = item.isLive,
                        url = item.url ?: ""
                    )
                } catch (e: Exception) {
                    null
                }
            }
    }

    // ─────────────────────────────────────────
    // COMMENTS
    // ─────────────────────────────────────────

    fun getComments(videoId: String): CommentsModel {
        val url = "https://www.youtube.com/watch?v=$videoId"
        val commentsInfo = CommentsInfo.getInfo(YouTube, url)

        val comments = commentsInfo.relatedItems
            .filterNotNull()
            .mapNotNull { comment ->
                try {
                    CommentModel(
                        id = comment.commentId,
                        author = comment.uploaderName ?: "Anonymous",
                        authorAvatarUrl = comment.uploaderAvatars.firstOrNull()?.url ?: "",
                        text = comment.commentText?.content ?: "",
                        likeCount = comment.likeCount,
                        isHeartedByUploader = comment.isHeartedByUploader,
                        isPinned = comment.isPinned,
                        publishedDate = comment.textualUploadDate ?: ""
                    )
                } catch (e: Exception) {
                    null
                }
            }

        return CommentsModel(
            videoId = videoId,
            comments = comments,
            nextPage = commentsInfo.nextPage?.url
        )
    }

    // ─────────────────────────────────────────
    // HELPER
    // ─────────────────────────────────────────

    private fun extractVideoId(url: String?): String {
        if (url == null) return ""
        // Extract from: https://www.youtube.com/watch?v=VIDEO_ID
        val regex = Regex("[?&]v=([^&]+)")
        return regex.find(url)?.groupValues?.get(1) ?: url
    }
}
