/**
 * types/index.ts
 *
 * TypeScript interfaces mirroring the backend Kotlin data classes.
 * Every API response maps to one of these types.
 * Keep these in sync with Models.kt on the backend.
 */

// ─────────────────────────────────────────────
// Service types
// ─────────────────────────────────────────────

/** A supported streaming service (YouTube, SoundCloud, etc.) */
export interface ServiceInfo {
  id: string               // e.g. "youtube", "soundcloud"
  name: string             // e.g. "YouTube", "SoundCloud"
  baseUrl: string
  supportsTrending: boolean
  supportsComments: boolean
}

/** All service IDs as a union type for type safety */
export type ServiceId =
  | 'youtube'
  | 'soundcloud'
  | 'peertube'
  | 'bandcamp'
  | 'mediaccc'
  | 'odysee'

// ─────────────────────────────────────────────
// Video & Stream types
// ─────────────────────────────────────────────

export interface VideoModel {
  id: string
  title: string
  uploader: string
  uploaderUrl: string
  duration: number
  viewCount: number
  uploadDate: string
  thumbnailUrl: string
  description?: string
  isLive: boolean
  url: string
  service: string          // which platform this came from
}

export interface StreamUrl {
  url: string
  quality: string
  format: string
  isVideoOnly: boolean
}

export interface SubtitleTrack {
  url: string
  languageCode: string
  languageName: string
  isAutoGenerated: boolean
}

export interface StreamModel {
  id: string
  title: string
  uploader: string
  uploaderUrl: string
  duration: number
  videoStreams: StreamUrl[]
  audioStreams: StreamUrl[]
  hlsUrl?: string
  subtitles: SubtitleTrack[]
  relatedVideos: VideoModel[]
  service: string
  thumbnailUrl: string
}

export interface SearchModel {
  query: string
  service: string
  items: VideoModel[]
  nextPage?: string
}

// ─────────────────────────────────────────────
// Channel types
// ─────────────────────────────────────────────

export interface ChannelModel {
  id: string
  name: string
  url: string
  description: string
  subscriberCount: number
  avatarUrl: string
  bannerUrl: string
  videos: VideoModel[]
  service: string
}

// ─────────────────────────────────────────────
// Comment types (YouTube only)
// ─────────────────────────────────────────────

export interface CommentModel {
  id: string
  author: string
  authorAvatarUrl: string
  text: string
  likeCount: number
  isHeartedByUploader: boolean
  isPinned: boolean
  publishedDate: string
}

export interface CommentsModel {
  videoId: string
  comments: CommentModel[]
  nextPage?: string
}

// ─────────────────────────────────────────────
// History types
// ─────────────────────────────────────────────

export interface HistoryModel {
  id: number
  videoId: string
  title: string
  uploader: string
  thumbnailUrl: string
  duration: number
  watchedAt: string
  watchedSeconds: number
  service: string
  url: string
}

// ─────────────────────────────────────────────
// Watchlist types
// ─────────────────────────────────────────────

export interface WatchlistModel {
  id: number
  videoId: string
  title: string
  uploader: string
  thumbnailUrl: string
  duration: number
  addedAt: string
  service: string
  url: string
}

// ─────────────────────────────────────────────
// Playlist types
// ─────────────────────────────────────────────

export interface PlaylistModel {
  id: number
  name: string
  description: string
  createdAt: string
  videoCount: number
  thumbnailUrl?: string
}

export interface PlaylistVideoModel {
  id: number
  videoId: string
  title: string
  uploader: string
  thumbnailUrl: string
  duration: number
  addedAt: string
  position: number
  service: string
  url: string
}

export interface PlaylistWithVideos {
  id: number
  name: string
  description: string
  createdAt: string
  videos: PlaylistVideoModel[]
}

// ─────────────────────────────────────────────
// Subscription types
// ─────────────────────────────────────────────

export interface SubscriptionModel {
  id: number
  channelId: string
  channelName: string
  channelUrl: string   // full URL — works for any service
  avatarUrl: string
  subscribedAt: string
  service: string
}

// ─────────────────────────────────────────────
// Download types
// ─────────────────────────────────────────────

export type DownloadStatus = 'PENDING' | 'DOWNLOADING' | 'COMPLETED' | 'FAILED'

export interface DownloadModel {
  id: number
  videoId: string
  title: string
  uploader: string
  thumbnailUrl: string
  filePath: string
  fileSize: number
  downloadedBytes: number
  status: DownloadStatus
  quality: string
  isAudioOnly: boolean
  createdAt: string
  service: string
}
